# Generated by Django 3.2.4 on 2023-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-created_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
