# Generated by Django 3.2.4 on 2023-05-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20230531_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='is_done',
        ),
    ]
